import type { GalleryItem } from '@/types';

export const GALLERY_CATEGORIES = [
  'All',
  'Action Figures',
  'Busts & Statues',
  'Minifigures',
  'Holders & Stands',
  'Custom Gifts',
  'Keychains',
] as const;

export type GalleryCategory = typeof GALLERY_CATEGORIES[number];

export const demoGalleryItems: GalleryItem[] = [
  {
    id: 'gal-01',
    title: 'All Might Dynamic Figure',
    category: 'Action Figures',
    image_url: '/images/products/allmight.png',
    description: 'Hand-crafted and airbrush painted All Might collectible figure with detailed muscular anatomy and anime shading.',
    tags: ['Anime', 'My Hero Academia', 'Hand Painted', 'Resin'],
    dimensions: '22cm Height',
    material: 'High-Detail Resin & Tough PLA',
    sort_order: 1,
    is_featured: true,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'gal-02',
    title: 'Itachi Uchiha with Akatsuki Cloak',
    category: 'Action Figures',
    image_url: '/images/products/itachi.png',
    description: 'Premium hand-painted Itachi Uchiha figure with cloud detailing on cloak and custom display stand.',
    tags: ['Anime', 'Naruto', 'Hand Painted', 'Akatsuki'],
    dimensions: '20cm Height',
    material: 'Resin + PLA Base',
    sort_order: 2,
    is_featured: true,
    is_active: true,
    created_at: '2026-01-12T10:00:00Z',
  },
  {
    id: 'gal-03',
    title: 'Superior Spider-Man with Mechanical Arms',
    category: 'Action Figures',
    image_url: '/images/products/superior-spiderman.png',
    description: 'Dynamic comic-accurate Superior Spider-Man sculpt featuring 4 poseable articulated metallic spider-arms.',
    tags: ['Marvel', 'Spider-Man', 'Action Figure', 'Hand Painted'],
    dimensions: '25cm Height',
    material: 'High Impact Resin',
    sort_order: 3,
    is_featured: true,
    is_active: true,
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'gal-04',
    title: 'Monkey D. Luffy Gear Bust',
    category: 'Busts & Statues',
    image_url: '/images/products/luffy-bust.png',
    description: 'Sculpted anime bust of Monkey D. Luffy featuring detailed straw hat texture, grin, and a sturdy stylized pillar pedestal.',
    tags: ['One Piece', 'Anime', 'Bust', 'Desk Display'],
    dimensions: '16cm Height',
    material: 'PLA / Hand Painted',
    sort_order: 4,
    is_featured: true,
    is_active: true,
    created_at: '2026-01-18T10:00:00Z',
  },
  {
    id: 'gal-05',
    title: 'Spider-Man Classic Bust',
    category: 'Busts & Statues',
    image_url: '/images/products/spiderman-bust-v3.png',
    description: 'Textured webbing and signature expressive mask eyes on a pedestal bust for comic collectors.',
    tags: ['Marvel', 'Spider-Man', 'Bust', 'Hand Finished'],
    dimensions: '15cm Height',
    material: 'Premium PLA',
    sort_order: 5,
    is_featured: true,
    is_active: true,
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'gal-06',
    title: 'Sasuke Uchiha Battle Stance',
    category: 'Action Figures',
    image_url: '/images/products/sasuke-figure.jpeg',
    description: 'Precision printed anime figure capturing Sasuke in mid-action with sword holster and custom paint finish.',
    tags: ['Anime', 'Naruto', 'Sasuke', 'Hand Painted'],
    dimensions: '18cm Height',
    material: 'Resin',
    sort_order: 6,
    is_featured: false,
    is_active: true,
    created_at: '2026-01-22T10:00:00Z',
  },
  {
    id: 'gal-07',
    title: 'Red Hulk Power Figure',
    category: 'Action Figures',
    image_url: '/images/products/red-hulk-figure-v3.png',
    description: 'Massive heavy-weight Red Hulk figure with defined muscle lines and aggressive battle pose.',
    tags: ['Marvel', 'Hulk', 'Statue', 'High Detail'],
    dimensions: '24cm Height',
    material: 'Solid Core PLA & Resin',
    sort_order: 7,
    is_featured: true,
    is_active: true,
    created_at: '2026-01-25T10:00:00Z',
  },
  {
    id: 'gal-08',
    title: 'Customised Chibi Funko Pops',
    category: 'Minifigures',
    image_url: '/images/products/customisable-funko-pops.png',
    description: 'Personalized mini figures customized according to customer photos, hairstyle, outfit, and accessories.',
    tags: ['Custom Order', 'Chibi', 'Gift', 'Hand Painted'],
    dimensions: '10cm - 12cm',
    material: 'Resin / PLA',
    sort_order: 8,
    is_featured: true,
    is_active: true,
    created_at: '2026-01-28T10:00:00Z',
  },
  {
    id: 'gal-09',
    title: 'Spider-Noir Trenchcoat Pop',
    category: 'Minifigures',
    image_url: '/images/products/spidernoir-funkopop.png',
    description: 'Monochromatic black and grey noir detective figure with fabric texture details.',
    tags: ['Marvel', 'Spider-Noir', 'Pop', 'Mini'],
    dimensions: '11cm Height',
    material: 'Smooth Resin',
    sort_order: 9,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'gal-10',
    title: 'Pennywise IT Horror Minifigure',
    category: 'Minifigures',
    image_url: '/images/products/it-minifigure.png',
    description: 'Creepy miniature figure with clown makeup detailing and red balloon accessory.',
    tags: ['Horror', 'Movie Collectible', 'Hand Painted'],
    dimensions: '12cm Height',
    material: 'Resin',
    sort_order: 10,
    is_featured: true,
    is_active: true,
    created_at: '2026-02-03T10:00:00Z',
  },
  {
    id: 'gal-11',
    title: 'Stitch Cute Minifigure',
    category: 'Minifigures',
    image_url: '/images/products/stich-minifigure-v3.png',
    description: 'Vibrant blue hand-painted Stitch miniature sitting happily on a display coin base.',
    tags: ['Disney', 'Stitch', 'Cute', 'Desk Companion'],
    dimensions: '8cm Height',
    material: 'Fine Resin',
    sort_order: 11,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'gal-12',
    title: 'Hello Kitty Cute Minifigure',
    category: 'Minifigures',
    image_url: '/images/products/hello-kitty-minifigure-v3.png',
    description: 'Iconic Hello Kitty figure with signature red bow and clean smooth matte finish.',
    tags: ['Sanrio', 'Hello Kitty', 'Gift', 'Pastel'],
    dimensions: '9cm Height',
    material: 'Smooth PLA',
    sort_order: 12,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-07T10:00:00Z',
  },
  {
    id: 'gal-13',
    title: 'MK1 Heavy Gaming Headset Stand',
    category: 'Holders & Stands',
    image_url: '/images/products/mk1-headset-stand-v2.png',
    description: 'Heavyweight Mortal Kombat dragon logo headset holder engineered to support over-ear headphones securely.',
    tags: ['Gaming', 'Desk Setup', 'Headphones', 'Mortal Kombat'],
    dimensions: '26cm Height',
    material: 'Reinforced Matte PLA',
    sort_order: 13,
    is_featured: true,
    is_active: true,
    created_at: '2026-02-08T10:00:00Z',
  },
  {
    id: 'gal-14',
    title: 'Ergonomic Controller Stand',
    category: 'Holders & Stands',
    image_url: '/images/products/controller-holder-v2.png',
    description: 'Custom sculpted dual-slot holder compatible with PS5 DualSense, Xbox Series X, and Nintendo Pro controllers.',
    tags: ['Gaming', 'PS5', 'Xbox', 'Desk Setup'],
    dimensions: '18cm x 12cm',
    material: 'Matte PLA',
    sort_order: 14,
    is_featured: true,
    is_active: true,
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'gal-15',
    title: 'Oni Mask Demon Controller Holder',
    category: 'Holders & Stands',
    image_url: '/images/products/oni-mask-controller-holder-v3.png',
    description: 'Fierce Japanese samurai Oni mask designed as a centerpiece controller stand with horns and fangs.',
    tags: ['Gaming', 'Oni Mask', 'Samurai', 'Hand Painted'],
    dimensions: '20cm Height',
    material: 'Painted PLA & Resin',
    sort_order: 15,
    is_featured: true,
    is_active: true,
    created_at: '2026-02-12T10:00:00Z',
  },
  {
    id: 'gal-16',
    title: 'Skull Gaming Controller Stand',
    category: 'Holders & Stands',
    image_url: '/images/products/skull-controller-holder-v2.png',
    description: 'Realistic bone-wash styled skull controller holder with textured cranium and teeth.',
    tags: ['Gaming', 'Skull', 'Desk Decor', 'Gothic'],
    dimensions: '16cm Height',
    material: 'Bone-White PLA + Acrylic Wash',
    sort_order: 16,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-14T10:00:00Z',
  },
  {
    id: 'gal-17',
    title: 'Hot Wheels Card Display Racks',
    category: 'Holders & Stands',
    image_url: '/images/products/hotwheel-card-holder-v2.png',
    description: 'Wall-mounted and shelf slide-in organizers designed specifically for carded die-cast cars and Hot Wheels collections.',
    tags: ['Hot Wheels', 'Diecast', 'Display Rack', 'Collector'],
    dimensions: 'Modular Grid',
    material: 'Durable PLA',
    sort_order: 17,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'gal-18',
    title: 'Die-cast Display Car Stand',
    category: 'Holders & Stands',
    image_url: '/images/products/car-stand-v2.png',
    description: 'Angled display ramp for model cars with engraved tyre tracks and customizable branding plaque.',
    tags: ['Cars', 'Display', 'Hot Wheels', 'Desk Stand'],
    dimensions: '12cm x 6cm',
    material: 'PLA',
    sort_order: 18,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-17T10:00:00Z',
  },
  {
    id: 'gal-19',
    title: 'Custom Photo Lithophane Lamp',
    category: 'Custom Gifts',
    image_url: '/images/products/customized-lithoplane-lamp-v2.png',
    description: 'Bespoke 3D curved lithophane lamp converting customer photos into glowing photographic reliefs when lit with warm LED.',
    tags: ['Custom Photo', 'Lithophane', 'Lamp', 'Memorial Gift'],
    dimensions: '15cm Diameter',
    material: 'Optical Translucent PLA',
    sort_order: 19,
    is_featured: true,
    is_active: true,
    created_at: '2026-02-19T10:00:00Z',
  },
  {
    id: 'gal-20',
    title: 'Valentine Keepsake Rose Heart',
    category: 'Custom Gifts',
    image_url: '/images/products/valentine-rose-v2.png',
    description: 'Everlasting 3D-sculpted rose heart display with custom engraved name tags on wooden look base.',
    tags: ['Valentine', 'Love Gift', 'Personalized', 'Rose'],
    dimensions: '14cm Height',
    material: 'Silk Red & Black PLA',
    sort_order: 20,
    is_featured: true,
    is_active: true,
    created_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'gal-21',
    title: 'Custom Business & Social QR Plaque',
    category: 'Custom Gifts',
    image_url: '/images/products/customized-qr-codes-v2.png',
    description: 'Dual-colour embossed 3D scannable QR stands for Instagram, WiFi, PayHere, and business shops.',
    tags: ['Business', 'QR Code', 'Custom Sign', 'Desk Stand'],
    dimensions: '10cm x 10cm',
    material: 'Dual Tone PLA',
    sort_order: 21,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-22T10:00:00Z',
  },
  {
    id: 'gal-22',
    title: 'Custom Pet Collar ID Tags',
    category: 'Custom Gifts',
    image_url: '/images/products/custom-pet-tags.png',
    description: 'Lightweight waterproof dog and cat collar tags with pet name on front and contact number on back.',
    tags: ['Pet Care', 'Custom Tag', 'Dog', 'Cat'],
    dimensions: '4cm x 3.5cm',
    material: 'Tough Impact PLA',
    sort_order: 22,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-23T10:00:00Z',
  },
  {
    id: 'gal-23',
    title: 'Vehicle Number Plate Replica Keychain',
    category: 'Keychains',
    image_url: '/images/products/number-plate-keychains.png',
    description: 'Personalized miniature Sri Lankan vehicle registration number plate keychain with provincial letters.',
    tags: ['Keychains', 'Vehicle', 'Personalized', 'Sri Lanka'],
    dimensions: '6cm x 2cm',
    material: 'Dual Color PLA + Stainless Ring',
    sort_order: 23,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-24T10:00:00Z',
  },
  {
    id: 'gal-24',
    title: "Minato's Flying Raijin Kunai Prop",
    category: 'Keychains',
    image_url: '/images/products/minatos-kunai-v2.png',
    description: 'Anime replica kunai dagger with three-pronged blade and etched handle seal wrapping.',
    tags: ['Anime', 'Naruto', 'Minato', 'Cosplay Prop'],
    dimensions: '18cm Prop / Mini Keychain',
    material: 'Tough PLA',
    sort_order: 24,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-25T10:00:00Z',
  },
  {
    id: 'gal-25',
    title: 'Geometric Low-Poly Cat Ornament',
    category: 'Custom Gifts',
    image_url: '/images/products/cat-ornament-v2.png',
    description: 'Modern minimalist low-polygon sculpted cat for bookshelf, desk, or gifting.',
    tags: ['Home Decor', 'Cat', 'Low Poly', 'Modern'],
    dimensions: '12cm Height',
    material: 'Matte PLA',
    sort_order: 25,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-26T10:00:00Z',
  },
  {
    id: 'gal-26',
    title: 'Dragon Wall & Desk Key Organiser',
    category: 'Holders & Stands',
    image_url: '/images/products/key-holder-dragon-v2.png',
    description: 'Fantasy dragon head with dual mounting hooks for holding keys and lanyards neatly.',
    tags: ['Dragon', 'Fantasy', 'Key Holder', 'Wall Decor'],
    dimensions: '15cm x 10cm',
    material: 'Reinforced PLA',
    sort_order: 26,
    is_featured: false,
    is_active: true,
    created_at: '2026-02-27T10:00:00Z',
  },
];
